/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package todolist;

public class App {

  public static void main(String[] args){
   UI ui = new UI();
    ui.addLine("XXUI");
    ui.addLine("I");
    ui.frame();
  }

}
